run:
  deadline: 90s

linters-settings:
  gocyclo:
    min-complexity: 25
  depguard:
    list-type: blacklist
    packages:
      - golang.org/x/net/context
      - github.com/gogo/protobuf/proto

linters:
  disable-all: true
  enable:
    - gocyclo
    - gofmt
    - goimports
    - revive
    - megacheck
    - misspell
    - govet
    - depguard
    - deadcode
    - ineffassign
    - varcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
